### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by shadowplay1** [MayiVT/colors-discord#3]
sorry, but ur package is useless

ppl can just import Util from discord.js and use their `resolveColor` method

```js
const { Util, Embed } = require('discord.js')

const embed = new Embed()
    .setTitle('hi')
    .setColor(Util.resolveColor('Green'))

message.reply({embeds: [embed]})
// and thats it
```

**Comment by MayiVT** [comment]
Im sorry to hear that,
I didn’t know about that Discord.js function, but yes it works, and I know people that prefer that npm. But thanks to comment that.
Have a nice day

**Comment by shadowplay1** [comment]
thanks, you too ^
